@CalendarWebsite.Server_HostAddress = https://localhost:7179

GET {{CalendarWebsite.Server_HostAddress}}/api/DataOnly_APIaCheckIn/GetAllUsersName
# Accept: application/json

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetAllUsersName

###

GET {{CalendarWebsite.Server_HostAddress}}/api/personalprofiles

###

@month=3
@year=2025
@userId=duydd1@vntt.com.vn
GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetRecordsByMonth?month={{month}}&year={{year}}&userId={{userId}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/  {{month}}&year={{year}}&userId={{userId}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetUserByUserId?month={{month}}&year={{year}}&userID={{userID}}

###

POST {{CalendarWebsite.Server_HostAddress}}/api/export/HelloWorld

###

GET {{CalendarWebsite.Server_HostAddress}}/api/export/ExportUserCheckinData?month={{month}}&year={{year}}&userID={{userID}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetAllCheckinInDay?month={{month}}&year={{year}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetAllCheckinInDay?month={{month}}&year={{year}}

###

@day=1
GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetAllCheckinInDay?day={{day}}&month={{month}}&year={{year}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/export/ExportUserCheckinDataByDay?day={{day}}&month={{month}}&year={{year}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/departments

###

GET {{CalendarWebsite.Server_HostAddress}}/api/departments

###

@id=5
GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetCheckInByDepartmentId?id={{id}}&day={{day}}&month={{month}}&year={{year}}

###

@dayTo=0
@monthTo=0
@yearTo=0
GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetAllCheckinInDayRange?day={{day}}&month={{month}}&year={{year}}&dayTo={{dayTo}}&monthTo={{monthTo}}&yearTo={{yearTo}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/export/TestExportNPOI

###

GET {{CalendarWebsite.Server_HostAddress}}/api/export/ExportUserCheckinDataNPOI?month={{month}}&year={{year}}&userID={{userID}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin

###

GET {{CalendarWebsite.Server_HostAddress}}/api/departments/33

###

GET {{CalendarWebsite.Server_HostAddress}}/api/departments/{{id}}

###

GET {{CalendarWebsite.Server_HostAddress}}/api/dataonly_apiacheckin/GetCheckInByDepartmentId?id={{id}}&day={{day}}&month={{month}}&year={{year}}&dayTo={{dayTo}}&monthTo={{monthTo}}&yearTo={{yearTo}}

###
